### ISSUE TITLE
Alien::PCRE2 Dependency Installation

### ISSUE THREAD

**Issue by wbraswell** [wbraswell/alien-jpcre2#2]
@plicease 
After I merged your pull request, then I removed the kludgy Alien::PCRE2 installation code from the BEGIN block in Makefile.PL:

https://github.com/wbraswell/alien-jpcre2/commit/dcfd15ce6446a8d695ca61fc2db351ebb8f19d11

I was hopeful that by removing my calls to Alien::PCRE2->dist_dir() in alienfile then you would also enable us to remove the kludy code.  Unfortunately, doing so put us right back to the error of "Can't locate Alien/PCRE2 in @INC":

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/252326599#L4489

For some unknown reason, I have always had to explicitly install Alien::Build (and IO::Socket::SSL) in my .travis.yml and appveyor.yml files before calling `cpanm --installdeps .` and if I disable this explicit installation then instead we get "Can't locate Alien/Build/MM.pm in @INC", obviously this is not good:

https://github.com/wbraswell/alien-jpcre2/commit/8658db560639427c9ed3475167e4934ae89f0134

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/252329804#L619

So what is the connection here, why do I have to explicitly install Alien::Build and why can't cpanm automatically find Alien::Build or Alien::PCRE2 to properly install?  Is there a connection between these 2 issues or not?  If they are 2 separate issues, then we need 2 separate answers...

**Comment by plicease** [comment]
You need to install Alien::PCRE2 before you run `cpanm --installdeps`.  Just like you are already pre-installing Alien::Build, since you do not have the META.json that has the required configure requires.

**Comment by wbraswell** [comment]
@plicease 
Okay I changed my .gitignore file to all MYMETA.json to be pushed to github

https://github.com/wbraswell/alien-jpcre2/blob/master/MYMETA.json

This seems to have gotten us farther but not 100% just yet:

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/252705000#L6128

At the end of the log we see:

`Successfully installed Alien-PCRE2-0.006000`

followed shortly by:

`Configuring Alien-JPCRE2-0.002000 failed`

Could this failure-at-the-end-after-seeming-success be linked back to the very start where Alien::JPCRE2's Makefile.PL crashes due to lack of Alien::Build::MM?

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/252705000#L660

`Configuring /home/travis/build/wbraswell/alien-jpcre2 ... Can't locate Alien/Build/MM.pm in @INC
BEGIN failed--compilation aborted at Makefile.PL line 8.`

**Comment by wbraswell** [comment]
@plicease 
Okay I added back in the line to force Travis to install Alien::Build:

https://github.com/wbraswell/alien-jpcre2/commit/f489075beea0ae733b0ef3c4c8b2846ec9bc7461

Alien::Build and Alien::Build::MM are properly installed, but now we have a crash because, again, it cannot find Alien::PCRE2 before it reaches the `cpanm --installdeps .` step:

`Can't locate Alien/PCRE2.pm in @INC ... at .../Module/Load.pm line 77`

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/252713531#L4488

If MYMETA.json would be loaded at the same time as META.json, then this seems to indicate that I am still being plagued by the same issues of Makefile.PL and/or alienfile attempting to load Alien::PCRE2 before the installdeps can get it installed.

**Comment by wbraswell** [comment]
@plicease 
I replaced MYMETA.json with META.json and now it works in Travis!  :-D

https://travis-ci.org/wbraswell/alien-jpcre2/builds/252739242

Now I just need to figure out why it is still failing to find gmake correctly in AppVeyor...

https://ci.appveyor.com/project/wbraswell/alien-jpcre2/build/1.0.54

**Comment by wbraswell** [comment]
Since it passes in Travis, I'll consider this issue closed and open a new issue for the Windows-specific build issues
